"""Mock external solver for vvkit pitch demo.

This script acts like a compiled C++/Fortran solver. It reads a configuration file
(generated by vvkit's Jinja2 templating), computes a 2nd-order discrete solution
for the 1D advection equation, and saves it in the expected NumPy (.npz) format.
"""

import argparse
import sys
from pathlib import Path
import numpy as np

def parse_input(filepath: Path) -> int:
    """Parse the Jinja2 generated input file for n_cells."""
    try:
        content = filepath.read_text(encoding="utf-8")
        for line in content.splitlines():
            if line.startswith("n_cells="):
                return int(float(line.split("=")[1]))
    except Exception as e:
        print(f"FATAL ERROR: Failed to parse input file {filepath}: {e}", file=sys.stderr)
        sys.exit(1)
    
    print(f"FATAL ERROR: n_cells not found in {filepath}", file=sys.stderr)
    sys.exit(1)

def run_solver(n_cells: int, out_file: Path) -> None:
    """Compute a 2nd-order Finite Volume solution."""
    print(f"MockSolver 1.0.0 initializing with {n_cells} cells...")
    
    dx = 1.0 / n_cells
    x_centers = np.linspace(0.5 * dx, 1.0 - 0.5 * dx, n_cells)
    
    # 2nd-order FV discretization artifact injected for the MMS exact solution sin(2*pi*x)
    u_exact = np.sin(2 * np.pi * x_centers)
    u_num = u_exact + 0.5 * (dx**2) * np.sin(2 * np.pi * x_centers)
    
    print("Computing solution arrays...")
    print(f"Writing output to {out_file}...")
    np.savez(out_file, x=x_centers, u=u_num)
    print("Simulation complete. Exiting normally.")

def main():
    parser = argparse.ArgumentParser(description="Mock Numerical Solver")
    parser.add_argument("input_file", type=Path, help="Path to solver input file")
    args = parser.parse_args()
    
    # In vvkit, the execution happens in an isolated workdir.
    # The solver should save its output in the current working directory.
    output_path = Path("solution.npz")
    
    n_cells = parse_input(args.input_file)
    run_solver(n_cells, output_path)

if __name__ == "__main__":
    main()
