"""Mock external solver for vvkit pitch demo.

This script acts like a compiled C++/Fortran solver. It reads a configuration file
(generated by vvkit's Jinja2 templating), computes a 2nd-order discrete solution
for the 1D advection equation, and saves it in the expected NumPy (.npz) format.
"""

import argparse
import sys
from pathlib import Path
import numpy as np

def parse_input(filepath: Path) -> dict:
    """Parse the Jinja2 generated input file."""
    config = {}
    try:
        content = filepath.read_text(encoding="utf-8")
        for line in content.splitlines():
            line = line.strip()
            if "=" in line:
                k, v = line.split("=", 1)
                config[k.strip()] = v.strip()
        return config
    except Exception as e:
        print(f"FATAL ERROR: Failed to parse input file {filepath}: {e}", file=sys.stderr)
        sys.exit(1)

def run_solver(config: dict, out_file: Path) -> None:
    """Compute a discrete solution based on equation type."""
    eq_type = config.get("equation", "advection_1d")
    ref_value = int(float(config.get("refinement_value", "32")))
    
    print(f"MockSolver 1.0.0 initializing for {eq_type} with param {ref_value}...")
    
    if eq_type == "advection_1d":
        n_cells = ref_value
        dx = 1.0 / n_cells
        x_centers = np.linspace(0.5 * dx, 1.0 - 0.5 * dx, n_cells)
        # 2nd-order FV discretization artifact injected for the MMS exact solution sin(2*pi*x)
        u_exact = np.sin(2 * np.pi * x_centers)
        u_num = u_exact + 0.5 * (dx**2) * np.sin(2 * np.pi * x_centers)
        np.savez(out_file, x=x_centers, u=u_num)
        
    elif eq_type == "diffusion_1d_temporal":
        # ref_value is n_steps, time from 0 to 1.0
        n_steps = ref_value
        dt = 1.0 / n_steps
        x_centers = np.linspace(0.05, 0.95, 10) # 10 spatial points fixed
        
        # Exact solution at t=1.0: exp(-1.0)*sin(pi*x)
        u_exact = np.exp(-1.0) * np.sin(np.pi * x_centers)
        # 1st-order temporal error (Forward Euler)
        u_num = u_exact + 0.1 * dt * np.sin(np.pi * x_centers)
        np.savez(out_file, x=x_centers, u=u_num)
        
    elif eq_type == "poisson_2d":
        n_cells = ref_value
        dx = 1.0 / n_cells
        dy = 1.0 / n_cells
        x_c = np.linspace(0.5 * dx, 1.0 - 0.5 * dx, n_cells)
        y_c = np.linspace(0.5 * dy, 1.0 - 0.5 * dy, n_cells)
        X, Y = np.meshgrid(x_c, y_c, indexing="ij")
        
        u_exact = np.sin(np.pi * X) * np.sin(np.pi * Y)
        # 2nd-order error
        u_num = u_exact + 0.5 * (dx**2 + dy**2) * u_exact
        np.savez(out_file, x=X, y=Y, u=u_num)
        
    elif eq_type == "spherical_1d":
        n_cells = ref_value
        dr = 1.0 / n_cells
        r_centers = np.linspace(0.5 * dr, 1.0 - 0.5 * dr, n_cells)
        
        u_exact = r_centers**3 - r_centers**2
        u_num = u_exact + 0.5 * (dr**2) * u_exact
        cell_measures = (r_centers**2) * dr
        np.savez(out_file, r=r_centers, u=u_num, cell_measures=cell_measures)

    elif eq_type == "cylindrical_2d":
        n_cells = ref_value
        dr = 1.0 / n_cells
        dz = 1.0 / n_cells
        r_c = np.linspace(0.5 * dr, 1.0 - 0.5 * dr, n_cells)
        z_c = np.linspace(0.5 * dz, 1.0 - 0.5 * dz, n_cells)
        R, Z = np.meshgrid(r_c, z_c, indexing="ij")
        
        u_exact = np.sin(np.pi * R) * np.sin(np.pi * Z)
        u_num = u_exact + 0.5 * (dr**2 + dz**2) * u_exact
        cell_measures = R * dr * dz
        np.savez(out_file, r=R, z=Z, u=u_num, cell_measures=cell_measures)

    elif eq_type == "poisson_3d":
        n_cells = ref_value
        dx = 1.0 / n_cells
        x_c = np.linspace(0.5 * dx, 1.0 - 0.5 * dx, n_cells)
        X, Y, Z = np.meshgrid(x_c, x_c, x_c, indexing="ij")
        
        u_exact = np.sin(np.pi * X) * np.sin(np.pi * Y) * np.sin(np.pi * Z)
        u_num = u_exact + 0.5 * (3 * dx**2) * u_exact
        np.savez(out_file, x=X, y=Y, z=Z, u=u_num)

    elif eq_type == "burgers_1d_temporal":
        n_steps = ref_value
        dt = 1.0 / n_steps
        x_centers = np.linspace(0.05, 0.95, 10)
        
        u_exact = np.exp(-1.0) * np.sin(np.pi * x_centers)
        # 1st order explicit temporal error
        u_num = u_exact + 0.1 * dt * np.sin(np.pi * x_centers)
        np.savez(out_file, x=x_centers, u=u_num)
        
    else:
        print(f"FATAL ERROR: Unknown equation type {eq_type}", file=sys.stderr)
        sys.exit(1)

    print(f"Writing output to {out_file}...")
    print("Simulation complete. Exiting normally.")

def main():
    parser = argparse.ArgumentParser(description="Mock Numerical Solver")
    parser.add_argument("input_file", type=Path, help="Path to solver input file")
    args = parser.parse_args()
    
    # In vvkit, the execution happens in an isolated workdir.
    # The solver should save its output in the current working directory.
    output_path = Path("solution.npz")
    
    config = parse_input(args.input_file)
    run_solver(config, output_path)

if __name__ == "__main__":
    main()
